# Linear Algebra from Scratch

Before diving into the code and intuition here, I **strongly recommend** watching the [Essence of Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) playlist by **3Blue1Brown** on YouTube.

It's a free, series that builds the most important thing in math: **visual intuition**. Most people learn linear algebra as a bunch of rules and formulas — this playlist shows you what's actually *happening*, geometrically. Once you see it, everything clicks.

>  You don't need to finish the whole playlist before starting here — even the first 4-5 videos will make a huge difference.

---

With that foundation, this repository walks through linear algebra **from scratch** — both the intuition behind every concept and the code to implement it. No libraries doing the heavy lifting. Just you, Python, and math.

### Magnitude of a vector

In [7]:
pip install ipywidgets

  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
  Using cached widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
  Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Using cached ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
Using cached widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)

   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   -------------------------- ------------- 2/3 [ipywidgets]
   ---------------------------------------- 3/


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Magnitude of a Vector

> **Before reading:** If you haven't already, watch the first few videos of [3Blue1Brown's Essence of Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab). It builds the visual intuition that makes everything below click instantly.

---

## What is Magnitude?

The magnitude of a vector is simply its **length** — how far it stretches from its tail to its tip. We write it as **|v|**.

The question is: *how do we calculate that length from just the numbers (components) of a vector?*

The answer comes from one of the oldest ideas in geometry — **Pythagoras' theorem**.

---

## Intuition in 2D

Think of a 2D vector like **v = [3, 4]**.

We know two things for free:
- **î** (i-hat) is the unit vector along x — it has length **1**
- **ĵ** (j-hat) is the unit vector along y — it has length **1**

So our vector is just saying: *"go 3 steps in x, then 4 steps in y."*

Now here's the key move — **drop a perpendicular from the tip of the vector straight down to the x-axis.**

What do you get? A right triangle where:
- the **base** is the x component (how far you went along x)
- the **height** is the y component (the perpendicular you just drew)
- the **hypotenuse** is the vector itself — and that's exactly what we want!

Since it's a right triangle, Pythagoras gives us:

$$|\vec{v}| = \sqrt{x^2 + y^2}$$

That's it. The magnitude is just the hypotenuse of the right triangle formed by the two components.

---

## Intuition in 3D

Now add a third dimension. Our vector is **v = [2, 3, 2]** — it goes somewhere in 3D space.

We can't directly apply Pythagoras to three things at once, but we can be clever about it — **apply it twice**.

**Step 1 — Take the shadow.**

Imagine shining a light straight down from above. The vector casts a **shadow onto the xz plane** (the floor). This shadow completely ignores the y component — it's as if you're looking at the vector from directly above and only seeing where it lands on the floor.

This shadow is a 2D vector with components x and z. Just like in 2D, drop a perpendicular and apply Pythagoras:

$$d = \sqrt{x^2 + z^2}$$

Now you have **d** — the length of the shadow (the floor diagonal).

**Step 2 — Stand it back up.**

Now forget about x and z separately. You have:
- **d** — the length of the shadow (one leg of a new right triangle)
- **y** — the perpendicular height from the floor up to the vector tip (other leg)
- **|v|** — the actual 3D vector (the hypotenuse you want)

Apply Pythagoras one more time:

$$|\vec{v}| = \sqrt{d^2 + y^2} = \sqrt{(\sqrt{x^2 + z^2})^2 + y^2} = \sqrt{x^2 + y^2 + z^2}$$

And that's why the 3D magnitude formula looks the way it does — it's just **Pythagoras applied twice**, once on the floor and once standing up.

---

## General Formula (any dimension)

This pattern extends to any number of dimensions. For a vector **v = [x₁, x₂, ..., xₙ]**:

$$|\vec{v}| = \sqrt{x_1^2 + x_2^2 + \dots + x_n^2} = \sqrt{\sum_{i=1}^{n} x_i^2}$$

Each dimension just adds another term under the square root — you're always finding the hypotenuse of a right triangle formed by "everything so far" and the new component.


### Will be adding visualization soon

If anyone wants me to do everything other than the intuition from scratch ill do it:

ex. sqrt , array and all..

In [4]:
import numpy as np

In [5]:
##2D
v1 = np.array([1,2])
value = v1[0]**2 +v1[1]**2
magnitude = np.sqrt(value)
print(f"magnitude of {v1} is {magnitude}")

magnitude of [1 2] is 2.23606797749979


In [6]:
##3D
##manual way for intuition
v2 = np.array([2,3,2])
projected_v2= v2[0]**2+v2[2]**2
projected = np.sqrt(projected_v2)
magnitude_v2 = projected**2+v2[1]**2
real_magnitude = np.sqrt(magnitude_v2)
print(f"first projected xz {projected} then second pythagoras {real_magnitude}")

first projected xz 2.8284271247461903 then second pythagoras 4.123105625617661


In [8]:
### faster way using library
v2 = np.array([2,3,2])
projected_v2= v2[0]**2+v2[1]**2+v2[2]**2
projected = np.sqrt(projected_v2)
print(f"{projected:.3f}")

4.123


# Normalizing a Vector

> **Normalization** = shrinking (or stretching) a vector so its magnitude becomes exactly **1**, without changing the direction it points.

## How to Normalize

To normalize a vector **v**, just divide every component by its magnitude:

$$\hat{v} = \frac{\vec{v}}{|\vec{v}|}$$

That's it. You're scaling the vector down (or up) so it lands exactly on the unit circle (in 2D) or unit sphere (in 3D).

**Example** — v = [3, 4]:

$$|\vec{v}| = \sqrt{3^2 + 4^2} = \sqrt{25} = 5$$

$$\hat{v} = \left[\frac{3}{5},\ \frac{4}{5}\right] = [0.6,\ 0.8]$$

Check: $\sqrt{0.6^2 + 0.8^2} = \sqrt{0.36 + 0.64} = \sqrt{1} = 1$ ✓

The direction is identical to the original — the vector just got scaled to length 1.

---

## Why Does This Work?

Think about it geometrically. If you divide a vector by its own length, you're asking: *"what fraction of my total length is each component?"*

The result always lands on the unit circle/sphere because you're normalizing the total stretch to 1. No matter how big or small the original vector was, after normalization it always sits on that boundary.

> **One edge case** — you can never normalize the zero vector **[0, 0, 0]** because dividing by zero is undefined. The zero vector has no direction, so normalization makes no sense for it.

---

## Applications

Machine Learning — Cosine Similarity

--We will learn more about this further.

NLP — Word Vectors

--further...



In [10]:
v = np.array([3, 4])

sum_of_squares = sum(x**2 for x in v)
magnitude      = np.sqrt(sum_of_squares)
unit_vector    = v / magnitude

print(f"original vector   : {v}")
print(f"magnitude         : {magnitude}")
print(f"normalized vector : {unit_vector}")
print(f"verify magnitude  : {np.sqrt(sum(x**2 for x in unit_vector)):.1f}")  # should be 1.0

original vector   : [3 4]
magnitude         : 5.0
normalized vector : [0.6 0.8]
verify magnitude  : 1.0


In [11]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])


In [11]:
##will come later

In [12]:
print(x1+x2)

[5 7 9]


In [13]:
print(x1*x2)

[ 4 10 18]


In [14]:
print(x2/x1)

[4.  2.5 2. ]


In [15]:
x3 = np.array([[1,2,3],[3,4,5],[6,7,8]])

In [16]:
print(x3*3)

[[ 3  6  9]
 [ 9 12 15]
 [18 21 24]]


In [17]:
print(x3/4)

[[0.25 0.5  0.75]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]


In [18]:
print(x3+3)

[[ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
print(x3*x1)

[[ 1  4  9]
 [ 3  8 15]
 [ 6 14 24]]


In [20]:
print(x1*x3)

[[ 1  4  9]
 [ 3  8 15]
 [ 6 14 24]]


In [21]:
print(x1*x2*x3)

[[  4  20  54]
 [ 12  40  90]
 [ 24  70 144]]


In [22]:
# Transpose of a matrix
A = [
    [1, 2, 3],
    [4, 5, 6]
]
rows = len(A)
cols = len(A[0])

In [23]:
rows , cols

(2, 3)

In [24]:
# STEP 1 - creates [[0,0],[0,0],[0,0]]
result = []
for c in range(cols):
    result.append([0] * rows)

# STEP 2 - your fill loop
for i in range(cols):
    for j in range(rows):
        result[i][j] = A[j][i]  # FILLS existing slots

In [25]:
result

[[1, 4], [2, 5], [3, 6]]

In [26]:
at = np.array(A).T

In [27]:
at

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
A = [
    [4, 7],
    [2, 6]
]

a = A[0][0]
b = A[0][1]
c = A[1][0]
d = A[1][1]

det = (a * d) - (b * c)
print(det)

10


In [29]:
inverse = [[d/det ,-(b)/det],[-(c)/det,a/det]]

In [30]:
inverse

[[0.6, -0.7], [-0.2, 0.4]]

In [31]:
import numpy as np

a_i = np.linalg.inv(A)




In [32]:
a_i

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [33]:
result = np.dot(A,inverse)

In [34]:
print(result)

[[ 1.00000000e+00  3.33066907e-16]
 [-1.11022302e-16  1.00000000e+00]]


Which formula are you asking about?

**Option 1 — Inverse formula for 2×2:**

$$A^{-1} = \frac{1}{ad-bc} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$$

You already coded this!

---

**Option 2 — The identity relationship:**

$$A \times A^{-1} = I$$

---

**Option 3 — How to find inverse using determinant:**

$$\text{if } \det(A) \neq 0 \rightarrow A^{-1} \text{ exists}$$
$$\text{if } \det(A) = 0 \rightarrow A^{-1} \text{ does NOT exist}$$

---

**Option 4 — For finding what input gave an output:**

$$A \times x = b$$
$$x = A^{-1} \times b$$

This is actually the most useful one in practice — used to **solve systems of equations!**

